// <auto-generated />
using System;
using CoffeeCodex.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeCodex.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoffeeCodexDbContext))]
    [Migration("20260329163259_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<int>("BrewCount")
                        .HasColumnType("integer")
                        .HasColumnName("brew_count");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_recipes_display_order");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeBrewSpecs", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<decimal?>("CoffeeDoseInGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("coffee_dose_in_grams");

                    b.Property<decimal?>("CoffeeYieldInGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("coffee_yield_in_grams");

                    b.Property<int?>("CupSizeInMl")
                        .HasColumnType("integer")
                        .HasColumnName("cup_size_in_ml");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("difficulty");

                    b.Property<int?>("MilkInMl")
                        .HasColumnType("integer")
                        .HasColumnName("milk_in_ml");

                    b.Property<int>("TimeInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_in_minutes");

                    b.HasKey("RecipeId");

                    b.ToTable("recipe_brew_specs", (string)null);
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("blob_url");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Position")
                        .HasDatabaseName("ix_recipe_images_recipe_id_position");

                    b.ToTable("recipe_images", (string)null);
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal>("QuantityValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity_value");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Position")
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id_position");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("instruction");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "StepNumber")
                        .HasDatabaseName("ix_recipe_steps_recipe_id_step_number");

                    b.ToTable("recipe_steps", (string)null);
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("RecipeId", "TagId")
                        .HasDatabaseName("ix_recipe_tags_recipe_id_tag_id");

                    b.ToTable("recipe_tags", (string)null);
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.Recipe", b =>
                {
                    b.HasOne("CoffeeCodex.Domain.Recipes.Author", "Author")
                        .WithMany("Recipes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeBrewSpecs", b =>
                {
                    b.HasOne("CoffeeCodex.Domain.Recipes.Recipe", "Recipe")
                        .WithOne("BrewSpecs")
                        .HasForeignKey("CoffeeCodex.Domain.Recipes.RecipeBrewSpecs", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeImage", b =>
                {
                    b.HasOne("CoffeeCodex.Domain.Recipes.Recipe", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("CoffeeCodex.Domain.Recipes.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeStep", b =>
                {
                    b.HasOne("CoffeeCodex.Domain.Recipes.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.RecipeTag", b =>
                {
                    b.HasOne("CoffeeCodex.Domain.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeCodex.Domain.Recipes.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.Author", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("BrewSpecs");

                    b.Navigation("Images");

                    b.Navigation("Ingredients");

                    b.Navigation("RecipeTags");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CoffeeCodex.Domain.Recipes.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });
#pragma warning restore 612, 618
        }
    }
}
